version: '3.8'

services:
  # redis:
  #   image: redis:7-alpine
  #   container_name: kvasir-research-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - kvasir-backend
  #   volumes:
  #     - redis_data:/data
  #   command: redis-server --appendonly yes

  experiments: &base-service
    build:
      context: ..
      dockerfile: kvasir-research/Dockerfile
    image: kvasir-research:latest
    container_name: kvasir-research-experiments
    command: ["tail", "-f", "/dev/null"]
    networks:
      - kvasir-backend
    # depends_on:
    #   - redis
    working_dir: /app/kvasir-research
    volumes: &shared-volumes
      - type: bind
        source: .
        target: /app/kvasir-research
      - type: bind
        source: ../kvasir-ontology
        target: /app/kvasir-ontology
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./projects_dir
        target: /app/projects_dir
      - type: bind
        source: ./exp
        target: /app/exp
      - type: bind
        source: ${HOME}/.modal.toml
        target:  /root/.modal.toml
    # Shouldn't need but docker desktop is trash and doesnt let me update so have it for now
    environment:
      - DOCKER_API_VERSION=1.41
  taskiq-worker:
    <<: *base-service
    container_name: kvasir-research-v1-worker
    command: ["sh", "-c", "cd /app/kvasir-research/src && taskiq worker kvasir_research.agents.v1.broker:v1_broker --tasks-pattern '**/*agent.py' -fsd --reload"]

# volumes:
#   redis_data:

networks:
  kvasir-backend:
    driver: bridge

